server:
  host: "localhost"
  port: 8080
  default_site: "main"

sites:
  main:
    hostname: "localhost"
    document_root: "./sites/main"
    index_file: "index.html"
    error_pages:
      404: "404.html"